# Site Information
baseURL: https://www.hayashi-lin.net/
publishDir: docs

# Compile-Time Setttings
#enableGitInfo: True

security:
  enableInlineShortcodes: true

module:
  imports:
  - path: github.com/aslemen/hugo-etch/v2

# Languages
languageCode: en-us
defaultContentLanguage: en
defaultContentLanguageInSubdir: True
hasCJKLanguage: True

languages:
  en:
    languageName: English
    title: Nori Hayashi
    weight: 1
    params:
      DateFormat: Jan 02, 2006
  ja:
    languageName: 日本語
    title: 林 則序
    weight: 2
    params:
      DateFormat: 2006-01-30

# Langauge-Indepdndent Parameters
params:
  copyright: Copyright © 2016–2024 Nori Hayashi